apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mt2y4ipxe-nodejs
  janus-idp.io/tekton: mt2y4ipxe-nodejs
  backstage.io/kubernetes-id: mt2y4ipxe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mt2y4ipxe-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
