apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: mt2y4ipxe-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mt2y4ipxe-nodejs 
  name: mt2y4ipxe-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mt2y4ipxe-nodejs
    weight: 100 
